from rest_framework.routers import DefaultRouter
from .views import TaskViewSet

# Create a router instance
router = DefaultRouter()

# Register the TaskViewSet. This automatically creates URLs for:
# /tasks/ (GET, POST)
# /tasks/{id}/ (GET, PUT, PATCH, DELETE)
router.register(r'tasks', TaskViewSet, basename='task')

# The urlpatterns will contain the routes generated by the router
urlpatterns = router.urls